name: Daily MLB Odds Update

on:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours
  workflow_dispatch:

jobs:
  update-odds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch_odds.py
        run: python fetch_odds.py

      - name: Commit and push updated odds.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add odds.json
          git commit -m "Auto-update odds.json"
          git push
